# Generated by Django 6.0.4 on 2026-04-07 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('impacts_quota', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Type d'absence",
                'db_table': 'absence_type',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Certification',
                'db_table': 'certification',
            },
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_hours_per_week', models.IntegerField()),
                ('leave_days_per_year', models.IntegerField()),
                ('night_shift_allowed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Type de contrat',
                'db_table': 'contract_type',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Rôle',
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('rule_type', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Règle métier',
                'db_table': 'rule',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('bed_capacity', models.IntegerField()),
                ('criticality_level', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Service',
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration_hours', models.IntegerField()),
                ('requires_rest_after', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Type de garde',
                'db_table': 'shift_type',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Personnel',
                'verbose_name_plural': 'Personnels',
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='CareUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_units', to='products.service')),
            ],
            options={
                'verbose_name': 'Unité de soins',
                'verbose_name_plural': 'Unités de soins',
                'db_table': 'care_unit',
            },
        ),
        migrations.CreateModel(
            name='ServiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ouvert', 'Ouvert'), ('ferme', 'Fermé'), ('sous-effectif', 'Sous-effectif')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='products.service')),
            ],
            options={
                'verbose_name': 'Statut du service',
                'db_table': 'service_status',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('min_staff', models.IntegerField()),
                ('max_staff', models.IntegerField()),
                ('care_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='products.careunit')),
                ('shift_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='products.shifttype')),
            ],
            options={
                'verbose_name': 'Garde / Créneau',
                'db_table': 'shift',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.specialty')),
            ],
            options={
                'verbose_name': 'Spécialité',
                'verbose_name_plural': 'Spécialités',
                'db_table': 'specialty',
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='products.shift')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='products.staff')),
            ],
            options={
                'verbose_name': 'Affectation de garde',
                'db_table': 'shift_assignment',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_services', to='products.staff'),
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('preference', 'Préférence'), ('contrainte', 'Contrainte')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('is_hard_constraint', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='products.staff')),
            ],
            options={
                'verbose_name': 'Préférence / Contrainte',
                'db_table': 'preference',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('workload_percent', models.IntegerField()),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='products.contracttype')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='products.staff')),
            ],
            options={
                'verbose_name': 'Contrat',
                'db_table': 'contract',
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('expected_end_date', models.DateField()),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('is_planned', models.BooleanField(default=True)),
                ('absence_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absences', to='products.absencetype')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='products.staff')),
            ],
            options={
                'verbose_name': 'Absence',
                'db_table': 'absence',
            },
        ),
        migrations.CreateModel(
            name='StaffCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_certifications', to='products.certification')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='products.staff')),
            ],
            options={
                'verbose_name': 'Certification du personnel',
                'db_table': 'staff_certification',
            },
        ),
        migrations.CreateModel(
            name='StaffLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('from_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_out', to='products.service')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='products.staff')),
                ('to_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_in', to='products.service')),
            ],
            options={
                'verbose_name': 'Prêt inter-services',
                'db_table': 'staff_loan',
            },
        ),
        migrations.CreateModel(
            name='StaffServiceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='products.service')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_assignments', to='products.staff')),
            ],
            options={
                'verbose_name': 'Affectation principale',
                'db_table': 'staff_service_assignment',
            },
        ),
        migrations.CreateModel(
            name='CertificationDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_cert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='products.certification')),
                ('required_cert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by', to='products.certification')),
            ],
            options={
                'verbose_name': 'Dépendance de certification',
                'db_table': 'certification_dependency',
                'unique_together': {('parent_cert', 'required_cert')},
            },
        ),
        migrations.CreateModel(
            name='PatientLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('patient_count', models.IntegerField()),
                ('occupancy_rate', models.FloatField()),
                ('care_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_loads', to='products.careunit')),
            ],
            options={
                'verbose_name': 'Charge patient',
                'db_table': 'patient_load',
                'unique_together': {('care_unit', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ShiftRequiredCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for_shifts', to='products.certification')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_certifications', to='products.shift')),
            ],
            options={
                'verbose_name': 'Certification requise pour garde',
                'db_table': 'shift_required_certification',
                'unique_together': {('shift', 'certification')},
            },
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_roles', to='products.role')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_roles', to='products.staff')),
            ],
            options={
                'verbose_name': 'Rôle du personnel',
                'db_table': 'staff_role',
                'unique_together': {('staff', 'role')},
            },
        ),
        migrations.CreateModel(
            name='StaffSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_specialties', to='products.specialty')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_specialties', to='products.staff')),
            ],
            options={
                'verbose_name': 'Spécialité du personnel',
                'db_table': 'staff_specialty',
                'unique_together': {('staff', 'specialty')},
            },
        ),
    ]
